spring:
  profiles:
    active: dev
  application:
    name: app
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://cdh:3306/app?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 123456
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 600000
      pool-name: hikari
      max-lifetime: 1800000
      connection-test-query: SELECT 1

mybatis:
  type-aliases-package: com.pain.yellow.app.domain.pojo
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB

# mybatis mapper 配置
mapper:
  mappers: com.pain.yellow.app.util.mapper.ApiMapper
  not-empty: false
  identity: MySQL

# 分页插件配置
#pagehelper:
#  helperDialect: mysql
#  supportMethodsArguments: true